// <auto-generated />
using System;
using CPW219_MVC_Core_CRUD_WithBugs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPW219_MVC_Core_CRUD_WithBugs.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20250806025757_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CPW219_MVC_Core_CRUD_WithBugs.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateOnly(2000, 1, 15),
                            FirstName = "Alice",
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateOnly(2001, 2, 20),
                            FirstName = "Bob",
                            LastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateOnly(2002, 3, 10),
                            FirstName = "Carol",
                            LastName = "Williams"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateOnly(2000, 4, 5),
                            FirstName = "David",
                            LastName = "Brown"
                        },
                        new
                        {
                            StudentId = 5,
                            DateOfBirth = new DateOnly(2001, 5, 25),
                            FirstName = "Eve",
                            LastName = "Jones"
                        },
                        new
                        {
                            StudentId = 6,
                            DateOfBirth = new DateOnly(2002, 6, 30),
                            FirstName = "Frank",
                            LastName = "Garcia"
                        },
                        new
                        {
                            StudentId = 7,
                            DateOfBirth = new DateOnly(2000, 7, 12),
                            FirstName = "Grace",
                            LastName = "Martinez"
                        },
                        new
                        {
                            StudentId = 8,
                            DateOfBirth = new DateOnly(2001, 8, 18),
                            FirstName = "Hank",
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            StudentId = 9,
                            DateOfBirth = new DateOnly(2002, 9, 22),
                            FirstName = "Ivy",
                            LastName = "Lee"
                        },
                        new
                        {
                            StudentId = 10,
                            DateOfBirth = new DateOnly(2000, 10, 8),
                            FirstName = "Jack",
                            LastName = "Walker"
                        },
                        new
                        {
                            StudentId = 11,
                            DateOfBirth = new DateOnly(2001, 11, 14),
                            FirstName = "Kara",
                            LastName = "Hall"
                        },
                        new
                        {
                            StudentId = 12,
                            DateOfBirth = new DateOnly(2002, 12, 19),
                            FirstName = "Leo",
                            LastName = "Allen"
                        },
                        new
                        {
                            StudentId = 13,
                            DateOfBirth = new DateOnly(2000, 1, 3),
                            FirstName = "Mona",
                            LastName = "Young"
                        },
                        new
                        {
                            StudentId = 14,
                            DateOfBirth = new DateOnly(2001, 2, 9),
                            FirstName = "Nate",
                            LastName = "Hernandez"
                        },
                        new
                        {
                            StudentId = 15,
                            DateOfBirth = new DateOnly(2002, 3, 15),
                            FirstName = "Olive",
                            LastName = "King"
                        },
                        new
                        {
                            StudentId = 16,
                            DateOfBirth = new DateOnly(2000, 4, 21),
                            FirstName = "Paul",
                            LastName = "Wright"
                        },
                        new
                        {
                            StudentId = 17,
                            DateOfBirth = new DateOnly(2001, 5, 27),
                            FirstName = "Quinn",
                            LastName = "Lopez"
                        },
                        new
                        {
                            StudentId = 18,
                            DateOfBirth = new DateOnly(2002, 6, 2),
                            FirstName = "Rita",
                            LastName = "Hill"
                        },
                        new
                        {
                            StudentId = 19,
                            DateOfBirth = new DateOnly(2000, 7, 7),
                            FirstName = "Sam",
                            LastName = "Scott"
                        },
                        new
                        {
                            StudentId = 20,
                            DateOfBirth = new DateOnly(2001, 8, 13),
                            FirstName = "Tina",
                            LastName = "Green"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
